# Generated by Django 4.2.3 on 2023-07-27 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Uzbekistan', 'UZBEKISTAN'), ('World', 'WORLD'), ('Finance', 'FINANCE'), ('Society', 'SOCIETY'), ('Science-techno', 'SCIENCE-TECHNOLOGY'), ('Sport', 'SPORTS'), ('Point of view', 'POINT OF VIEW'), ('AD', 'ADVERTISEMENT')], db_index=True, max_length=14, verbose_name='Category')),
                ('region', models.CharField(choices=[('Tashkent cit', 'Tashkent city'), ('Tashkent reg', 'Tashkent region'), ('Karakalpakstan', 'Karakalpakstan'), ('Andijan', 'Andijan'), ('Fergana', 'Fergana'), ('Namangan', 'Namangan'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Khorazm', 'Khorazm'), ('Surkhandarya', 'Surkhandarya'), ('Kashkadarya', 'Kashkadarya'), ('Jizzakh', 'Jizzakh'), ('Sirdarya', 'Sirdarya'), ('Navoi', 'Navoi')], db_index=True, max_length=14, verbose_name='Region')),
                ('cover_img', models.ImageField(upload_to='cover_imgs/', verbose_name='Cover photo')),
                ('body', models.TextField(verbose_name='Body')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('created_at', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='AudioNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('audio', models.FileField(upload_to='audio/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('created_at', 'slug')},
            },
        ),
    ]
