# Generated by Django 4.2.3 on 2023-07-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_textnewsmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textnewsmodel',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='author_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='category_en',
            field=models.CharField(choices=[('uzbekistan', 'UZBEKISTAN'), ('world', 'WORLD'), ('finance', 'FINANCE'), ('society', 'SOCIETY'), ('science-techno', 'SCIENCE-TECHNOLOGY'), ('sport', 'SPORTS'), ('point-of-view', 'POINT OF VIEW'), ('ad', 'ADVERTISEMENT')], db_index=True, max_length=14, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='category_ru',
            field=models.CharField(choices=[('uzbekistan', 'UZBEKISTAN'), ('world', 'WORLD'), ('finance', 'FINANCE'), ('society', 'SOCIETY'), ('science-techno', 'SCIENCE-TECHNOLOGY'), ('sport', 'SPORTS'), ('point-of-view', 'POINT OF VIEW'), ('ad', 'ADVERTISEMENT')], db_index=True, max_length=14, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='category_uz',
            field=models.CharField(choices=[('uzbekistan', 'UZBEKISTAN'), ('world', 'WORLD'), ('finance', 'FINANCE'), ('society', 'SOCIETY'), ('science-techno', 'SCIENCE-TECHNOLOGY'), ('sport', 'SPORTS'), ('point-of-view', 'POINT OF VIEW'), ('ad', 'ADVERTISEMENT')], db_index=True, max_length=14, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='cover_img_en',
            field=models.ImageField(null=True, upload_to='cover_imgs/', verbose_name='Cover photo'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='cover_img_ru',
            field=models.ImageField(null=True, upload_to='cover_imgs/', verbose_name='Cover photo'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='cover_img_uz',
            field=models.ImageField(null=True, upload_to='cover_imgs/', verbose_name='Cover photo'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='created_at_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='created_at_uz',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='region_en',
            field=models.CharField(choices=[('tashkent-city', 'Tashkent city'), ('tashkent-reg', 'Tashkent region'), ('karakalpakstan', 'Karakalpakstan'), ('andijan', 'Andijan'), ('fergana', 'Fergana'), ('namangan', 'Namangan'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('khorazm', 'Khorazm'), ('surkhandarya', 'Surkhandarya'), ('kashkadarya', 'Kashkadarya'), ('jizzakh', 'Jizzakh'), ('sirdarya', 'Sirdarya'), ('navoi', 'Navoi')], db_index=True, max_length=14, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='region_ru',
            field=models.CharField(choices=[('tashkent-city', 'Tashkent city'), ('tashkent-reg', 'Tashkent region'), ('karakalpakstan', 'Karakalpakstan'), ('andijan', 'Andijan'), ('fergana', 'Fergana'), ('namangan', 'Namangan'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('khorazm', 'Khorazm'), ('surkhandarya', 'Surkhandarya'), ('kashkadarya', 'Kashkadarya'), ('jizzakh', 'Jizzakh'), ('sirdarya', 'Sirdarya'), ('navoi', 'Navoi')], db_index=True, max_length=14, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='region_uz',
            field=models.CharField(choices=[('tashkent-city', 'Tashkent city'), ('tashkent-reg', 'Tashkent region'), ('karakalpakstan', 'Karakalpakstan'), ('andijan', 'Andijan'), ('fergana', 'Fergana'), ('namangan', 'Namangan'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('khorazm', 'Khorazm'), ('surkhandarya', 'Surkhandarya'), ('kashkadarya', 'Kashkadarya'), ('jizzakh', 'Jizzakh'), ('sirdarya', 'Sirdarya'), ('navoi', 'Navoi')], db_index=True, max_length=14, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='updated_at_en',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='updated_at_ru',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='updated_at_uz',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='view_count_en',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='view_count_ru',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='textnewsmodel',
            name='view_count_uz',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
